### ISSUE TITLE
Numerical beagle sample labels not parsed correctly

### ISSUE THREAD

**Issue by OliverPStuart** [fgvieira/ngsDist#14]
I get the following error running ngsDist. I haven't had problems before this and ngsDist works great with every other beagle file I've passed it. All arguments (n_ind, n_sites, etc.) are double-checked and correct.

```
file=test.beagle.gz
name=$(echo $file | sed 's/\.beagle\.gz//g')
n_site=$(gzcat $file | awk 'END{print NR-1}')
n_ind=$(gzcat $file | awk 'NR == 1 {print (NF-3)/3}')

$ ~/ngsdist/ngsdist \
--geno ${name}.beagle.gz \
--n_ind ${n_ind} \
--n_sites ${n_site} \
--out ${name}.dist \
--n_boot_rep 100 \
--boot_block_size 1 \
--evol_model 1 \
--seed 45645 \
--probs \
--pairwise_del \
--indep_geno

[...]

==> Reading genotype data

=====
ERROR: [read_geno] wrong GENO file format. Less fields than expected!
=====

	: Undefined error: 0
```

I suspect the problem is my sample names; I rename the sample labels in the beagle header earlier in my pipeline for easier manipulation, and some of the sample labels are purely numerical. Running on an unmodified beagle (where sample labels are Ind0, Ind1, etc.) works fine, and then if I modify just one of the samples to have a numerical label, I reproduce the error.

Attached is a test file which gives me the error: [test.beagle.gz](https://github.com/fgvieira/ngsDist/files/5656943/test.beagle.gz)

Is it possible to update the beagle parsing to allow numerical sample labels?

**Comment by fgvieira** [comment]
I've tried running your example and it runs fine; even with a file with the labels (`1`, `10`, `11A`).

Can you try with the latest version?
