### ISSUE TITLE
Boostrap replicated

### ISSUE THREAD

**Issue by aguilar-gomez** [fgvieira/ngsDist#16]
I am running ngsDist and trying to generate bootstrap replicates. I only get one valid matrix (the first) and the "bootstrap replicates" are just matrices full of nans. 
This is the command I am using:

`ngsDist --n_threads 10 --seed 12345 --verbose 1 --geno myfile.beagle.gz --probs --n_ind 347 --n_sites 2737682 --labels pum.labels --pos myfile.beagle.pos --n_boot_rep 100 --boot_block_size 5000000 --out pum.dist `

it did not give me any error:
```
==> Analysis will be run in 60031 combinations
==> GZIP input file (never BINARY)
==> Reading labels
==> Reading positions file
==> Reading genotype data
> Header found! Skipping line...
==> Analyzing full dataset...
==> Bootstrap replicate # 1 ...
==> Bootstrap replicate # 2 ...
==> Bootstrap replicate # 3 ...
...
==> Bootstrap replicate # 99 ...
==> Bootstrap replicate # 100 ...
==> Freeing memory...
Done!

```
I generated the beagle file with angsd:
```
angsd -bam $bamlist -out myfile -setMinDepthInd 1 -minMapQ 25 -minQ 25 -rem
ove_bads 1 -uniqueOnly 1 -only_proper_pairs 1 -GL 1 -doMaf 1 -doMajorMinor 4 -doGlf 2 -nThreads 10 -
ref $REF -doCounts 1 -sites oksites_angsdv4 -rf oksites_angsdv4.rf -minMaf 0.05

```

**Comment by fgvieira** [comment]
Hi @aguilar-gomez,

from your command it seems you have around 2,7M sites but are asking for a `--boot_block_size` of 5M. Can you try with a smaller `--boot_block_size` (its default value is `1`)?

Any reason you want a `--boot_block_size` so big?

**Comment by aguilar-gomez** [comment]
Hi,

My reference genome is really big ~6Gb. I have 2.7 million sites but very spaced, I thought my chunk size had to be big but maybe I overdid it. It generated the trees without error for another project I was doing. I just tried again changing the chunk size to 50k and it seems to be generating the bootstrap trees. I think I do not understand very well what the chunk size does, is it like a window? Does it sample a position every x (chunk size) base pair or is it an average?

Thank you and sorry, I think it is just my problem not understanding this option.

**Comment by fgvieira** [comment]
When doing bootstrap, `ngsDist` will randomly sample blocks of the alignment into a new alignment, and make a tree for each of these alignments. That option controls the size of the block.

If in doubt, you can use the default value.

**Comment by aguilar-gomez** [comment]
ok thank you. The last question, then if I used the default option of bootstrap, the algorithm samples one base pairs randomly to do the trees, right? What percentage of the total sites does it use for each bootstrap tree?

**Comment by fgvieira** [comment]
It will always make an alignment the same size as the original alignment, but sampling `--boot_block_size` base pairs at a time.
