### ISSUE TITLE
missing ../../ngsSim directory for test. Where can it be found?

### ISSUE THREAD

**Issue by init-js** [fgvieira/ngsDist#7]
The docs mention `make && make test`

but the repo/examples/test.sh file refers to a folder `../../ngsSim` which I suppose is from a different repository.

where could i find the data ?

**Comment by init-js** [comment]
Ah. It's meant to be used from https://github.com/mfumagalli/ngsTools

(which does contain  ngsSim and ngsDist submodules)

**Comment by fgvieira** [comment]
Yes, exactly!
