### ISSUE TITLE
Any way to breakup the input to decrease job size?

### ISSUE THREAD

**Issue by kellybarr** [fgvieira/ngsDist#8]
My initial attempt to run a 64GB job failed.  I have the option of going up to 128GB on my server, but this would take forever to start.  Is there anyway to split up the datafile for analyses and then to recombine?  Perhaps run it scaffold by scaffold?  Thanks.

**Comment by fgvieira** [comment]
there might be, but it is not very straightforward and I have not tested it.
I think you can:

- run ngsDist with option `--tot_sites 1` for each scaffold; this will give the number of differences between samples per scaffold
- sum all the matrices, to get the total number of pair-wise differences
- divide by the total number of sites
