### ISSUE TITLE
BEAGLE format?

### ISSUE THREAD

**Issue by kellybarr** [fgvieira/ngsDist#9]
I've been futilely trying to run and ngsDist analysis.  The BEAGLE file I'm using is made with this command:  

angsd -P 8 -b my_list -ref my_ref -anc my_anc -out my_out -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -trim 0 -C 50 -baq 1 -minMapQ 20 -minQ 20 -minInd 50 -setMinDepth 25 -setMaxDepth 400 -doCounts 1 -GL 1 -doMajorMinor 1 -doMaf 1 -skipTriallelic 1 -doGlf 2 -doGeno 32 -doPost 1 -SNP_pval 1e-6 

Do you see any issues?

**Comment by fgvieira** [comment]
Dear @kellybarr,

not sure what you are trying to do but, from your command it seems you are calculating genotype posterior probabilities, not likelihoods.
Even though `ngsDist` will work with prob, it has only been tested with likelihoods.
